# O segredo está aqui: troque 'mem' por 'file' e dê um caminho
# ./data/meubanco cria uma pasta 'data' no seu projeto com o banco dentro
spring.datasource.url=jdbc:h2:file:./data/meubanco
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console para você visualizar as tabelas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# IMPORTANTE: Use 'update' para ele não apagar o que já existe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true